# Generated by Django 6.0.2 on 2026-04-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('benzin', 'Benzin'), ('dizel', 'Dizel'), ('elektr', 'Elektr'), ('gibrid', 'Gibrid')], default='benzin', max_length=20)),
                ('transmission', models.CharField(choices=[('mexanika', 'Mexanika'), ('avtomat', 'Avtomat'), ('variator', 'Variator')], max_length=20)),
                ('engine_volume', models.FloatField(verbose_name='Dvigatel hajmi')),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
            },
        ),
    ]
